### ISSUE TITLE
Seems to be an empty module

### ISSUE THREAD

**Issue by plicease** [oodler577/p5-Alien-OpenMP#1]
Doesn't seem to actually implement the methods described in documentation:

```
% perl -MAlien::OpenMP -E 'say Alien::OpenMP->cflags'
Can't locate object method "cflags" via package "Alien::OpenMP" at -e line 1.
```

**Comment by mohawk2** [comment]
That is currently correct (so far)! You're on `#pdl` and will have seen the surrounding discussion?

**Comment by oodler577** [comment]
@plicease see #2 

review/feedback is appreciated - first time creating one of these :)

**Comment by mohawk2** [comment]
Will close this - basically, we're working on it! @plicease If you're minded to "watch" this repo and weigh in, that would be enormously valuable!
